### ISSUE TITLE
2.1.x `--parallel` breaking change

### ISSUE THREAD

**Issue by kategengler** [ember-cli/ember-exam#245]
`ember exam --split 2 --parallel --random` is no longer working in 2.1.x (a breaking change). It no longer parallelizes and also does not randomize 

>"Randomizing tests with seed: false". The `--random` argument would seem to be swallowed as the value for `--parallel`.

https://github.com/ember-cli/ember-exam/commit/358d4aef63a0bae9f9b81af51d2bd337b9fc1fe2#diff-87b833f28b68e5193e797dd72f03c7a8L23 is a breaking change that changes `--parallel` from a Boolean argument to a Number

If I attempt to run `ember exam --split=2 --parallel=2`, I get an error `EmberExam: When used with `split` or `partition`, `parallel` does not accept a value other than 1.`

**Comment by stefanpenner** [comment]
Cc @step2yeung

**Comment by stefanpenner** [comment]
I think may rerelease prior to the offending code. I’ll be free tonight to do so.

**Comment by stefanpenner** [comment]
re-released v2.0.3 as v2.1.5 🎉

We will release 2.1.4 as 3.0.0, with updated changelog and verification that the upgrade docs address this issue

**Comment by choheekim** [comment]
I’ve spent a bit of time in this issue
https://github.com/ember-cli/ember-exam/issues/245

Parallelization, `ember exam --split=2 --parallel` doesn’t work when ember-exam setup is not set properly due to new customized test-loader.

Randomization and parallelization together doesn’t work because now we accept a value for `parallel`, for instance `ember exam --load-balance --parallel=2`, and passing something after `--parallel` it takes it as an argument and this is where the issue is coming from when running `ember exam --split=2 --parallel --random`.

e.g.
`ember exam --split=2 --parallel`  parallel value is 1 `ember exam --split=2 --parallel --random` parallel value is undefined as we only accept parallel value to be `number`

Will address this issue
