### ISSUE TITLE
Confusing parallel setting

### ISSUE THREAD

**Issue by amk221** [ember-cli/ember-exam#270]
We need to have `parallel: -1` in our testem config.

But we _also_ need to have `--parallel=1` when running ember exam.

**Comment by step2yeung** [comment]
Hi @amk221 

I can understand the confusion, so let me start with some context:

You are correct that testem config needs `parallel:-1`.. this actually allows ember-exam's parallel to work
[See how testem uses the parallel value](https://github.com/testem/testem/blob/b39fdded0aa91a7eb2e86e5567a4619919946e29/lib/app.js#L374): 
```
    let limit = this.config.get('parallel');

    let options = {};

    if (limit && limit >= 1) {
      options.concurrency = parseInt(limit);
    } else {
      options.concurrency = Infinity;
    }
```
Unfortunately, testem defaults parallel to 1.. making `parallel: -1` in the testem config necessary. So in a way, it is the key for testem to allow any number of parallel browser. My question is, do you have to deal with testem config often? In my experience, the testem config stays pretty static for me.

So coming to ember-exam's parallel value, it is the actual value used to determine the number of parallel browsers.

I hope this helps with understanding why there's both.  With that said, do you a PR on testem to default parallel to -1 would be helpful?

**Comment by grayt0r** [comment]
👋@step2yeung, thanks for the info!

We had a little bit of extra confusion when using `--parallel` along with `--split`. We are mainly using this combo to attempt to get the full test suite to run faster in our local environments.

The full command we were running was:
```
ember exam --split=4 --parallel --random
```

After the change to `--parallel` to accept a number we updated this to:
```
ember exam --split=4 --parallel=1 --random
```

I think my confusion comes from the fact I have to set `--parallel` to `1` when using split, and the `--split` value seems to end up controlling the number of parallel browsers.

Am I misunderstanding how these arguments work together? Am I missing a better way?

Thanks for the help, much appreciated!

(FYI I work with @amk221)

**Comment by step2yeung** [comment]
Ah yes, thank you for sharing your use case, it helps me understand why this problem came bout.

This is an unfortunate part of using commander, which handles the CLI code.
Since `--parallel` now takes a value. To pass the value, commander consider a value is passed via `=` or anything that comes after a space. So in the case of 
```
ember exam --split=4 --parallel --random
```
the value of `parallel` becomes `--random`

But since `--random` also takes a parameter, you are sorta stuck to use `--parallel=1` when using `--random`

So you are understanding the arguments correctly. It's not immediately clear how to fix this problem when there are two parameter that takes a value but also have a default value. But it certainly can be addressed.

**Comment by grayt0r** [comment]
That all makes sense, thanks!

We suddenly started seeing only a 1/4 of our tests run with the `ember exam --split=4 --parallel --random` command and it wasn't immediately obviously why (turns out it was like you said, the args were being parsed as `--parallel=--random` which I assume was then ignored as it's nonsense!).

One final question if I may, should we now be using `--load-balance` instead? i.e.
```
ember exam --parallel=4 --load-balance
```

Thanks again for the help :)

**Comment by step2yeung** [comment]
The new `--load-balance` command should improve the distribution of tests between the browsers.
If you are not satisfied with the speed from `--split=4 --parallel` then it's definitely worth a try!

It inherently runs the test modules (or test file) in a sudo random manner.
