### ISSUE TITLE
--random without argument not working

### ISSUE THREAD

**Issue by timiyay** [ember-cli/ember-exam#310]
I've recently upgraded from ember-exam 1.0.0 to 3.0.2, which has caused our randomization to stop working.

We execute our test with:

```sh
ember exam --reporter=dot --split=4 --parallel --random
```

Since upgrading, running these tests now prints:

```
Randomizing tests with seed: false
```

I saw a similar problem mentioned in this closed issue (https://github.com/ember-cli/ember-exam/issues/245#issuecomment-480995653), but there was no open issue tracking this bug.

**Comment by choheekim** [comment]
Hi @timiyay,
Staring ember exam v.3.0.0 the option `parallel` takes an option value, which means that whatever comes after `parallel` it will take it as a value, e.g. in your case `parallel=--random`.
https://github.com/ember-cli/ember-exam/blob/master/README.md#test-load-balancing

you can
1.  downgrade ember exam to 2.1.x
2.  You can pass see value to random or to parallel
e.g.
```
$ ember exam --reporter=dot --split=4  --random=<seed-value> --parallel
$ ember exam --reporter=dot --split=4 --parallel='true' --random
```
3. Use load-balance instead of split with parallel to load balance test with multiple browsers
$ ember exam --reporter=dot --parallel=4 --load-balance=true --random

**Comment by timiyay** [comment]
Thanks for the reply @choheekim. That makes sense. I’ll refactor accordingly, with a possible docs PR for anything I couldn’t get from the README.

**Comment by timiyay** [comment]
@choheekim I've tried the steps you've suggested, but no luck.

All of the 3 `ember exam` commands you suggested don't enable randomization, and I get `Randomizing tests with seed: false`.

This suggests the code doesn't work as expected, and may be a bug.

**Comment by choheekim** [comment]
@timiyay do you mind sharing how you set up ember exam?

Starting version 3.0.0 you need to execute ember exam’s ‘start()’ function. 
https://github.com/ember-cli/ember-exam/blob/master/README.md#how-to-use

**Comment by timiyay** [comment]
No worries @choheekim, thanks for taking the time.

Here's our typical `test-helper.js` after our ember-exam 3.0.0 upgrade:

```js
import { setApplication } from '@ember/test-helpers'
import start from 'ember-exam/test-support/start'
import Application from '../app'
import config from '../config/environment'

setApplication(Application.create(config.APP))
start()
```

**Comment by timiyay** [comment]
OK I've come back to this and it's now working as expected.

I often run npm-based commands with `yarn exec`, which is where I was hitting issues. `yarn exec ember exam --random` would not work, but `ember exam --random` does.
