### ISSUE TITLE
What are the optimal split/parallel settings?

### ISSUE THREAD

**Issue by erichonkanen** [ember-cli/ember-exam#354]
What are the optimal settings for running tests with ember-exam?

The docs explain the settings between split, partition, parallel, load-balance, and random, but it's a bit confusing to determine what the ideal settings should be.

Our project is a typical ember project and we use travis for ci/cd.

For both local & travis, what determines the optimal parallel setting? What about number of splits? Can you or should you still use randomization when using split and parallel? What about load-balance?

Currently I'm using this command, with `parallel: process.env.EMBER_EXAM_SPLIT_COUNT` in testem:
`ember exam --split=9 --parallel --load-balance`

It would be great to have more information regarding how to construct an ideal command for both local and travis, thank you!

**Comment by choheekim** [comment]
Hi @erichonkanen,

There are two ways to execute tests in parallel in ember-exam now:
1. --split=[number] --parallel
2. --load-balance --parallel=[number]

Option #2, with --load-balance, doesn't `require` test modules upfront instead it `requires` test modules when browsers make a request to receive test modules. While Option #1 requires test modules, splits test modules into numbers of buckets passed by `split`, and pass the buckets to browsers. 

if you would like to use `--random` with option #1 it is not required to pass a value to parallel because `parallel` now takes a value.
e.g. ember exam --split=[num] --parallel=1 --random
